### ISSUE TITLE
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'path' cannot be null

### ISSUE THREAD

**Issue by ghost** [JessyLedama/domain-manager#1]
Hello,

I tried to test your project but got the following error:

Illuminate \ Database \ QueryException
PHP 8.1.20
10.28.0
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'path' cannot be null

insert into
  `master_site_availables` (
    `path`,
    `domainId`,
    `serverName`,
    `serverAlias`,
    `proxyPass`,
    `proxyPassReverse`,
    `rewriteCond1`,
    `rewriteCond2`,
    `updated_at`,
    `created_at`
  )
values
  (
    ?,
    2,
    domain.com,
... etc

As above, the question mark ? is causing an error mentioned above.

Any solution?

**Comment by JessyLedama** [comment]
This system works by creating a sites-available file (/etc/apache2/sites-available) and a service file (/etc/systemd/system) when you create a domain. I have updated the system to use these two locations as default, but they can be overwritten by creating new paths for each in the admin panel.
